//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDemo.Client.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IJsonService")]
    public interface IJsonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonService/UploadJson", ReplyAction="http://tempuri.org/IJsonService/UploadJsonResponse")]
        string UploadJson(byte[] bytes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IJsonServiceChannel : WCFDemo.Client.Services.IJsonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class JsonServiceClient : System.ServiceModel.ClientBase<WCFDemo.Client.Services.IJsonService>, WCFDemo.Client.Services.IJsonService {
        
        public JsonServiceClient() {
        }
        
        public JsonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JsonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JsonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JsonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UploadJson(byte[] bytes) {
            return base.Channel.UploadJson(bytes);
        }
    }
}
